// Mock data for testing the product management UI
export const mockProducts = [
  {
    id: "1",
    name: "iPhone 15 Pro",
    description:
      "The latest iPhone with advanced camera system and A17 Pro chip",
    price: 999.99,
    stock: 25,
    categoryId: "1",
    category: "Phones",
    status: "active",
    image: "/src/assets/images/image 57.png",
    sku: "IPH15PRO-256",
    weight: "187g",
    vendor: "Apple Store",
    brand: "Apple",
    createdAt: "2024-01-15T10:30:00Z",
    updatedAt: "2024-01-20T14:45:00Z",
    specifications: {
      "Screen Size": "6.1 inches",
      Storage: "256GB",
      Color: "Natural Titanium",
      Battery: "Up to 23 hours",
    },
  },
  {
    id: "2",
    name: 'MacBook Pro 14"',
    description: "Powerful laptop with M3 Pro chip for professionals",
    price: 1999.99,
    stock: 12,
    categoryId: "2",
    category: "Computers",
    status: "active",
    image: "/src/assets/images/image 58.png",
    sku: "MBP14-M3-512",
    weight: "1.55kg",
    vendor: "Apple Store",
    brand: "Apple",
    createdAt: "2024-01-10T09:15:00Z",
    updatedAt: "2024-01-18T16:20:00Z",
    specifications: {
      Processor: "M3 Pro",
      Memory: "18GB",
      Storage: "512GB SSD",
      Display: "14-inch Liquid Retina XDR",
    },
  },
  {
    id: "3",
    name: "Samsung Galaxy Watch 6",
    description: "Advanced smartwatch with health monitoring features",
    price: 349.99,
    stock: 30,
    categoryId: "3",
    category: "SmartWatch",
    status: "active",
    image: "/src/assets/images/image 59.png",
    sku: "SGW6-44MM",
    weight: "28.7g",
    vendor: "Samsung Store",
    brand: "Samsung",
    createdAt: "2024-01-12T11:45:00Z",
    updatedAt: "2024-01-19T13:30:00Z",
    specifications: {
      Display: "1.5-inch AMOLED",
      Battery: "Up to 40 hours",
      "Water Resistance": "5ATM",
      Connectivity: "Bluetooth 5.3",
    },
  },
  {
    id: "4",
    name: "Sony A7 IV Camera",
    description: "Full-frame mirrorless camera with 33MP sensor",
    price: 2499.99,
    stock: 8,
    categoryId: "4",
    category: "Camera",
    status: "active",
    image: "/src/assets/images/image 61.png",
    sku: "SONY-A7IV",
    weight: "659g",
    vendor: "Sony Store",
    brand: "Sony",
    createdAt: "2024-01-08T08:20:00Z",
    updatedAt: "2024-01-16T15:10:00Z",
    specifications: {
      Sensor: "33MP Full-frame",
      Video: "4K 60p",
      Autofocus: "759 phase-detection points",
      Stabilization: "5-axis IBIS",
    },
  },
  {
    id: "5",
    name: "Bose QuietComfort 45",
    description: "Premium noise-cancelling headphones with exceptional sound",
    price: 329.99,
    stock: 45,
    categoryId: "5",
    category: "Headphones",
    status: "active",
    image: "/src/assets/images/image 57.png",
    sku: "BOSE-QC45",
    weight: "240g",
    vendor: "Bose Store",
    brand: "Bose",
    createdAt: "2024-01-05T12:00:00Z",
    updatedAt: "2024-01-14T10:25:00Z",
    specifications: {
      "Noise Cancellation": "Acoustic Noise Cancelling",
      "Battery Life": "Up to 24 hours",
      Connectivity: "Bluetooth 5.1",
      Comfort: "TriPort acoustic architecture",
    },
  },
  {
    id: "6",
    name: "PlayStation 5",
    description: "Next-generation gaming console with lightning-fast loading",
    price: 499.99,
    stock: 15,
    categoryId: "6",
    category: "Gaming",
    status: "active",
    image: "/src/assets/images/ps5-slim.png",
    sku: "PS5-DISC",
    weight: "3.9kg",
    vendor: "Sony Store",
    brand: "Sony",
    createdAt: "2024-01-03T14:30:00Z",
    updatedAt: "2024-01-12T09:45:00Z",
    specifications: {
      Storage: "825GB SSD",
      Graphics: "AMD RDNA 2",
      CPU: "AMD Zen 2",
      "Ray Tracing": "Hardware-accelerated",
    },
  },
];

export const mockCategories = [
  {
    id: "1",
    name: "Phones",
    description: "Smartphones and mobile devices",
    icon: "📱",
    productCount: 1,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "2",
    name: "Computers",
    description: "Laptops, desktops, and computing devices",
    icon: "💻",
    productCount: 1,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "3",
    name: "SmartWatch",
    description: "Smartwatches and wearable technology",
    icon: "⌚",
    productCount: 1,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "4",
    name: "Camera",
    description: "Digital cameras and photography equipment",
    icon: "📷",
    productCount: 1,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "5",
    name: "Headphones",
    description: "Audio equipment and headphones",
    icon: "🎧",
    productCount: 1,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "6",
    name: "Gaming",
    description: "Gaming consoles and accessories",
    icon: "🎮",
    productCount: 1,
    createdAt: "2024-01-01T00:00:00Z",
  },
];

// Helper function to simulate API delay
export const delay = (ms = 1000) =>
  new Promise((resolve) => setTimeout(resolve, ms));

// Helper function to simulate API errors
export const simulateError = (probability = 0.1) => {
  if (Math.random() < probability) {
    throw new Error("Simulated API error");
  }
};
